### ISSUE TITLE
Fix the MainComponent for Responsiveness

### ISSUE THREAD

**Issue by DevPatel1023** [DevPatel1023/React_Js-Internship-Project#1]
for medium and large devices the maincomponent is getting hide behind the sidebar 
![image](https://github.com/DevPatel1023/React_Js-Internship-Project/assets/118754663/d93c443e-bf0a-4873-9377-80e4df36c9a6)

**Comment by Devang-IO** [comment]
you can change the positioning of sidebar from sticky to relative
